version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13" # only touch after reading docs/maintaining/supported-python-versions.md

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - connector_telegram
        - connector_slack
        - database_matrix
        - connector_matrix

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
