# .readthedocs.yml

version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
          - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
